export const COUNTRIES: { name: string; flag: string }[] = [
  { name: 'Cameroon', flag: '🇨🇲' },
  { name: 'Nigeria', flag: '🇳🇬' },
  { name: 'Chad', flag: '🇹🇩' },
  { name: 'Central African Republic', flag: '🇨🇫' },
  { name: 'Gabon', flag: '🇬🇦' },
  { name: 'Equatorial Guinea', flag: '🇬🇶' },
  { name: 'Congo', flag: '🇨🇬' },
  { name: 'DR Congo', flag: '🇨🇩' },
  { name: "Côte d'Ivoire", flag: '🇨🇮' },
  { name: 'Senegal', flag: '🇸🇳' },
  { name: 'Benin', flag: '🇧🇯' },
  { name: 'Togo', flag: '🇹🇬' },
  { name: 'Mali', flag: '🇲🇱' },
  { name: 'Niger', flag: '🇳🇪' },
  { name: 'Burkina Faso', flag: '🇧🇫' },
  { name: 'Ghana', flag: '🇬🇭' },
  { name: 'Guinea', flag: '🇬🇳' },
  { name: 'France', flag: '🇫🇷' },
  { name: 'United States', flag: '🇺🇸' },
  { name: 'United Kingdom', flag: '🇬🇧' },
  { name: 'Canada', flag: '🇨🇦' },
  { name: 'Other', flag: '🌍' },
];
